### ISSUE TITLE
Download-Manager doesn't create new files

### ISSUE THREAD

**Issue by Coretool** [piranna/download-manager#4]
As I already said, the download-manager doesn't create new files from patches. I think I found the bug in your `loadFile`method. I think it doesn't recognize `dev/null` as valid files so it doesn't work. Do you wanna fix or shall I ?

**Comment by piranna** [comment]
If you are into the mood give it a try ;-)

**Comment by Coretool** [comment]
I removed 
```js 
if(content === false)
return console.error('Context sanity check failed:',patch)
```
and it creates a new file but doesn't really write to it (only the name)...

**Comment by piranna** [comment]
`jsdiff` return `false` on failure, maybe you should do the fix there... How are you doing to read the input file (/dev/null)?

**Comment by Coretool** [comment]
I thought about creating a new file if the `oldPath` is `/dev/null`...

**Comment by piranna** [comment]
> I thought about creating a new file if the oldPath is /dev/null...

Don't check for the actual value, reading from `/dev/null` will always gets you an empty file, so you can use it directly.

**Comment by Coretool** [comment]
So this works for `fs.writeFile` ?

**Comment by piranna** [comment]
Yes, and for readfile too.

**Comment by piranna** [comment]
Did you get any luck with this? If you want you can create a pull-request although it doesn't work so I can be able to review your code and help you...

**Comment by piranna** [comment]
This should be already fixed in master, clossing. Feel free to open it again is the issue still happen.
